### ISSUE TITLE
Add password reset with your phone (iOS and Android)

### ISSUE THREAD

**Issue by amatsui** [robinneb/golfzing#36]
Add SMS password reset to Forgot Password authentication process.
Nexmo allows for provider routing and conversion (receipts) data.

Using Nexmo's solution, the iOS app will allow a user to reset their password using SMS verification.
- User will enter in their code sent via SMS.
- https://docs.nexmo.com/messaging/sms-api
- https://docs.nexmo.com/messaging/conversion-api/api-reference#authentic
- https://docs.nexmo.com/messaging/conversion-api
- Conversion data must be confidential.
![golfzing_r5_0005_6](https://cloud.githubusercontent.com/assets/22970324/21122731/d5fa1322-c088-11e6-9809-80cea974ff98.jpg)
![golfzing_r5_0003_4](https://cloud.githubusercontent.com/assets/22970324/21122732/d5fbea4e-c088-11e6-8225-959f9c80c894.jpg)
![golfzing_r5_0004_5](https://cloud.githubusercontent.com/assets/22970324/21122733/d5ff5468-c088-11e6-9b25-8c9da4a4a9bf.jpg)

**Quality Assurance**
- no need for text to speech
- Create a request to send an SMS.
- Check the response codes and ensure that you sent the request correctly.
- Your message is delivered to the handset. The user's handset returns a delivery receipt.
- If you set callback in the request, check that your user received your SMS correctly.

**Comment by robinneb** [comment]
@amatsui Acceptance Criteria:
- Tap Forgot Password
- Player is taken to the Forgot Password Screen and see a prompt that...
Then what happens..
Then what happens...
etc.
