### ISSUE TITLE
Attach the Zingpoints API at Facebook Sign-Up

### ISSUE THREAD

**Issue by robinneb** [robinneb/golfzing#39]
Requirements: Call the Zingpoints API upon a successful Facebook Sign-Up. 

Specifications: Once the app has received a successful authentication back from FB OAuth that a user has successfully granted permission to our app and the user has completed Sign Up as a Facebook registrant, the new account will begin calling the Zingpoints API. 

Acceptance Criteria: Upon a successful sign-up with Facebook a user earns 250 Zingpoints automatically.

**Comment by drubage** [comment]
@robinneb the code to add points to people's account's via signup or other actions happens automatically in the Drupal code, there doesn't need to be an extra explicit API call to achieve that.

**Comment by robinneb** [comment]
Thanks @drubage  - going to close this request out then.
