### ISSUE TITLE
Sign up with Nexmo for SMS Password Verification 

### ISSUE THREAD

**Issue by robinneb** [robinneb/golfzing#47]
In order to help a user reset their password, we will want to use Nexmo to verify that the number is valid, send a code to the user and reset the password. 

**Requirements:** 
User taps Sign Up. They are required to enter in their password as part of the sign up process 
Once they complete their sign up, they will be taken to a screen that asks them to confirm their number by entering in the code that was just sent via SMS (requires Nexmo integration)

The user enters in their code 
![011617_golfzing_enter4digits_04](https://cloud.githubusercontent.com/assets/3999278/22186969/1b09d336-e0b3-11e6-94cc-2f913fa11322.jpg)

A success screen is shown 
![011617_golfzing_mobilesuccess_03](https://cloud.githubusercontent.com/assets/3999278/22186972/24fe44f8-e0b3-11e6-96cd-e2d01561e0c8.jpg)

The user is taken to the view Tee Times landing page. 

**Specifications:** 
When a user confirms their sign up, Nexmo will validate that their number is a mobile number and not a landline or work line. If the number is a mobile device, the Nexmo platform will send a text message with a code to validate the account. This phone number will also be added to the Golfzing user record which we will use to validate their account in the event of forgotten password.

**Comment by digitalbrandgroup** [comment]
Sign up with nexmo for SMS password verification: this entire section is confirmed as currently "on hold" until further notice
