### ISSUE TITLE
Authenticate with USGA for GHIN [story in progress]

### ISSUE THREAD

**Issue by robinneb** [robinneb/golfzing#6]
Requirements: As a user, I want to to be able to link my GHIN to my Golfzing user profile. 

Specifications: Example text only -  On the registration screen a user will be able to associate their GHIN number. Authentication is available through creating a developer profile at www.ghin.org

**Comment by drubage** [comment]
FYI we do not have any functionality related to the USGA or handicaps at this time. We started down the path of looking into it for some GHIN integration Ryan wanted to do with Players Clubs but we didn't get too far and the USGA people are not very helpful on development questions. I am not sure if this will be included for the initial app or not.

**Comment by robinneb** [comment]
Closing out this issue for now given the complexity.

**Comment by robinneb** [comment]
Closing out this issue for now given the complexity.
