### ISSUE TITLE
Connect with Nexmo for SMS verification

### ISSUE THREAD

**Issue by robinneb** [robinneb/golfzing#72]
Requirements: Authenticate with Nexmo in order to validate a user's phone number at Sign Up and to process Account recovery via SMS

We will only need the Verify SDK in order to validate phone numbers
https://docs.nexmo.com/verify/verify-sdk-for-iOS

Associated stories 
Sign Up Verification - https://github.com/robinneb/golfzing/issues/71
Forgot Password: https://github.com/robinneb/golfzing/issues/3

**Comment by digitalbrandgroup** [comment]
SMS verification: this entire section is confirmed as currently "on hold" until further notice

**Comment by digitalbrandgroup** [comment]
@robinneb 
Ashley had confirmed that SMS have been removed, with that said, please kindly revise the forgotpassword flow and provide the updated PSD

thanks

**Comment by robinneb** [comment]
Closing this ticket - removed from the app
